---
version: "3.9"

services:

  api:
    build:
      context: .

    container_name: api
    command: python -m uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/bewise_ai/.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
        context: .

    container_name: migrations
    volumes:
      - ./.env:/biwise_ai/.env
    command: python -m alembic upgrade heads
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
      image: postgres:15.0-alpine
#      ports:
#        - "5432"
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      restart: always
      container_name: postgres
      volumes:
        - ./postgresdata:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
        interval: 5s
        timeout: 5s
        retries: 15
...